// lib/data.ts — POWO Apple Health dashboard data.
// The full dataset is the 6-month export in lib/imported-health-export.ts
// (auto-generated by scripts/convert-export.mjs). `baseHealthData` below carries
// only the CURATED, non-derived bits (owner, profile, schema). Everything
// data-driven — summary, monthly, daily, vo2, workouts, pushups, sleep — is
// computed from the export by normalizeHealthExport().
import type { HealthData } from './types'
import { latestHealthExport } from './imported-health-export'
import { normalizeHealthExport } from './normalize-health-export'

const ZERO = { date: '', value: 0 }

const baseHealthData: HealthData = {
  meta: {
    owner: 'Coley',
    generated_at: '2026-06-02T00:00:00-05:00', // overridden from export
    source: 'Apple HealthKit',                  // overridden from export
    period: { start: '', end: '', days: 0 },    // overridden from export
    schema_version: '3.0',
    notes: '',                                  // overridden from export
  },
  profile: {
    age_band: 'mid-20s',
    primary_goal: 'Best shape of life',
    weight_kg: 79.4,        // overridden from export bodyMeasurement
    weight_lbs: 175,
    weight_date: '2026-02-25',
    active_lifestyle: ['Golf', 'Pickleball', 'Skateboarding', 'Walking'],
    training_focus: 'Cardio base + structured strength build',
    current_constraints: [
      'Left shoulder pain on internal rotation (loaded pressing limited)',
      'Left hip discomfort (intermittent)',
    ],
    equipment: ['Apple Watch', '44 lb barbell'],
  },
  // ── Below are stubs; normalizeHealthExport() replaces all of them. ──
  summary: {
    period_totals: { total_steps: 0, total_active_kcal: 0, total_exercise_min: 0, total_distance_km: 0, total_workouts: 0, total_flights_climbed: 0 },
    averages: { avg_daily_steps: 0, avg_active_kcal: 0, avg_resting_hr: 0, avg_hrv_ms: 0, avg_exercise_min: 0 },
    best_days: { max_steps: ZERO, max_active_kcal: ZERO, max_exercise_min: ZERO },
    vo2_max_progression: { first: ZERO, peak: ZERO, current: ZERO },
  },
  monthly: {},
  daily: [],
  vo2_max: [],
  workouts: [],
  workout_summary: [],
  pushups: { unit: 'reps', weeks: [] },
  sleep: {
    nights: [],
    coverage_note: '',
    summary: { nights_with_data: 0, avg_in_bed_hours: 0, min_in_bed_hours: 0, max_in_bed_hours: 0, stdev_hours: 0, typical_bedtime: '', typical_wake: '', naps: 0 },
  },
}

export const healthData: HealthData = normalizeHealthExport(baseHealthData, latestHealthExport)
